### ISSUE TITLE
Tab Close Button Position

### ISSUE THREAD

**Issue by ohnnyj** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#131]
A feature request.

I've always disliked having the close button on the right. If I want to close multiple tabs in succession and they have different string lengths then I have to jump around to find the button. Adding the following will move them to the left:

```css
::shadow .tabbed-pane-header .tabbed-pane-header-tab {
  position: relative !important;
}
::shadow.tabbed-pane-header .tabbed-pane-header-tab-title {
  margin-left: 12px !important;
}
::shadow.tabbed-pane-header .tabbed-pane-close-button {
  position: absolute !important;
  top: 50% !important;
  left: 0 !important;
  margin: 0 !important;
  transform: translateY(-50%) !important;
}
```
Forked: https://github.com/ohnnyj/chrome-devtools-zerodarkmatrix-theme.
