### ISSUE TITLE
A suggestion for readability

### ISSUE THREAD

**Issue by orloxx** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#29]
In my desktop version I added this line of code at the beginning of the file because for readability purposes I like the line-height to be more separated:

``` css
/*--READABILITY--*/
#-webkit-web-inspector .outline-disclosure ol li,
#-webkit-web-inspector .text-editor .inner-container .webkit-line-content,
#-webkit-web-inspector .text-editor-lines .inner-container .webkit-line-number,
#-webkit-web-inspector #console-view .console-message {
    line-height: 16px;
}
```

Sorry if there's another way of doing this that I don't know about.
