### ISSUE TITLE
Network Headers Request Payload (parsed) style

### ISSUE THREAD

**Issue by wulftone** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#34]
There are some unstyled bits in the Network -> Headers -> Request Payload (view parsed) section.

![image](https://f.cloud.github.com/assets/142784/906667/c6716d0e-fcc5-11e2-8d27-199bf7480644.png)

Can be fixed like so:

``` css
#-webkit-web-inspector .resource-headers-view .console-formatted-object,
#-webkit-web-inspector .resource-headers-view .console-formatted-array {
    color: #CCC !important;
}
```

Though you may want to do something better.  : )
